name: hojiakbar_s_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  intl: ^0.18.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: K2D
      fonts: 
        - asset: assets/fonts/K2DRegular.ttf
          weight: 400
        - asset: assets/fonts/K2DExtraLight.ttf
          weight: 300
        - asset: assets/fonts/K2DSemiBold.ttf
          weight: 600
        - asset: assets/fonts/K2DLight.ttf
          weight: 300
        - asset: assets/fonts/K2DMedium.ttf
          weight: 500
    - family: Rubik
      fonts: 
        - asset: assets/fonts/RubikRegular.ttf
          weight: 400
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
